import { FundingCard, FundingType } from "./components.js";

export enum FundingName {
    InvestorTrust = "Investor Trust",
    PreciseTools = "Precision Tools",
    MarketSurge = "Market Surge",
    CubeDraw = "Cube Draw",
    SharedUpgrade = "Shared Upgrade",
    PowerRefund = "Power Refund",
    PriorityWindow = "Priority Window",
    SelectiveDraw = "Selective Draw",
    ConverterVoucher = "Converter Voucher",
    VictoryResearch = "Victory Research",
    PowerSwap = "Power Swap",
    InvestorBonus = "Investor Bonus",
    ExtraTrapSlot = "Extra Trap Slot",
    EmergencyReset = "Emergency Reset",
    InvestorFavor = "Investor Favor",
    MiniStorage = "Mini-Storage",
    LoanedTechnician = "Loaned Technician",
    MarketPeek = "Market Peek",
    StorageInsurance = "Storage Insurance",
    RnDGrant = "R&D Grant",
    LateStageFunding = "Late-Stage Funding",
    ReagentVoucher = "Reagent Voucher",
    TemporarySlot = "Temporary Slot",
    ExperimentalCatalyst = "Experimental Catalyst",
    EfficiencyAudit = "Efficiency Audit",
    ReactorGrant = "Reactor Grant",
    BackupGenerator = "Backup Generator",
    ResearchCollaboration = "Research Collaboration",
    OverclockedReactor = "Overclocked Reactor",
    PublicDemonstration = "Public Demonstration"
}

export const fundingCards: Partial<FundingCard>[] = [
    {name: FundingName.PublicDemonstration,	type: FundingType.Ongoing,	effect: 'Chose an upgrade to turn without using it and gain ⭐ equal to its cost.'},
    {name: FundingName.OverclockedReactor,	type: FundingType.Ongoing,	effect: 'Use one of the upgrades remaining in the market during testing.'},
    {name: FundingName.ResearchCollaboration,	type: FundingType.Ongoing,	effect: 'During the Test phase copy the effect of one other player’s Trap upgrade.'},
    {name: FundingName.BackupGenerator,	type: FundingType.Permanent,	effect: 'Your exhaust upgrade can be used an unlimited number of times during Testing.'},
    {name: FundingName.ReactorGrant,	type: FundingType.Permanent,	effect: 'When using a Heater upgrade also gain +2 ⭐'},
    {name: FundingName.EfficiencyAudit,	type: FundingType.Permanent,	effect: 'Your upgrades that require 2 cubes now only require 1 cube (your choice).'},    
    {name: FundingName.ExperimentalCatalyst,	type: FundingType.Ongoing,	effect: 'Convert one cube of your choice into any color once per round.'},
    {name: FundingName.ReagentVoucher,	type: FundingType.Ongoing,	effect: 'Take either 1 white or 1 blue cube from the pool each round.'},
    {name: FundingName.TemporarySlot,	type: FundingType.Permanent,	effect: 'You may place an upgrade of any type here.'},    
    {name: FundingName.LateStageFunding,	type: FundingType.Instant,	effect: 'In phase III, draw 2 funding cards.'},
    {name: FundingName.RnDGrant,	type: FundingType.Instant,	effect: 'Draw 2 funding cards, keep 1, and discard the other.'},
    {name: FundingName.StorageInsurance,	type: FundingType.Permanent,	effect: 'Gain 2 ⭐ for each leftover cube you don\'t store after testing.'},
    {name: FundingName.MarketPeek,	type: FundingType.Permanent,	effect: 'When drawing random cards for upgrades: draw 2 upgrades, keep 1, and place the other on the bottom of the deck.'},
    {name: FundingName.EmergencyReset,	type: FundingType.Instant,	effect: 'After all of the power tokens are revealed, you may swap any number with your available tokens.'},
    {name: FundingName.LoanedTechnician,	type: FundingType.Ongoing,	effect: 'Use one upgrade on your board twice during the testing phase.'},
    {name: FundingName.MiniStorage,	type: FundingType.Permanent,	effect: 'You may store up to 2 blue or white cubes here between rounds.'},
    {name: FundingName.InvestorBonus,	type: FundingType.Instant,	effect: 'Gain +4 ⭐ for each upgrade you purchased this phase.'},
    {name: FundingName.ExtraTrapSlot,	type: FundingType.Permanent,	effect: 'Gain +1 storage slot (store 1 additional cube between rounds).'},    
    {name: FundingName.InvestorFavor,	type: FundingType.Permanent,	effect: 'Gain +3 ⭐ whenever you buy an upgrade that costs 3 or more.'},
    {name: FundingName.CubeDraw,	type: FundingType.Permanent,	effect: 'When gaining cubes you may take them from 2 piles.  Combine those piles for other players after completion.'},
    {name: FundingName.SelectiveDraw, type: FundingType.Instant,	effect: 'Place 2 blue cubes and 2 white cubes in the bag and mix.  Next, draw 4 cubes.'},
    {name: FundingName.PowerRefund,	type: FundingType.Permanent,	effect: 'After testing, keep one cube used for scoring.  You must have room for it in storage.'},    
    {name: FundingName.PriorityWindow,	type: FundingType.Instant,	effect: 'Add +2 to your power when resolving Funding.'},    
    {name: FundingName.SharedUpgrade,	type: FundingType.Permanent,	effect: 'Upgrades cost 1 less.'},
    {name: FundingName.ConverterVoucher,	type: FundingType.Ongoing,	effect: 'During testing, activate one upgrade without paying its requirement.'},    
    {name: FundingName.PowerSwap,	type: FundingType.Instant,	effect: 'Move all tokens in your cooldown pool to your available pool.'},                
    {name: FundingName.MarketSurge,	type: FundingType.Permanent,	effect: 'When gaining cubes, take +1 (max 4) above the power assigned.'},
    {name: FundingName.VictoryResearch,	type: FundingType.Instant,	effect: 'Score 5 ⭐ immediately.'},
    {name: FundingName.InvestorTrust,	type: FundingType.Ongoing,	effect: 'Once per round, discard another funding card to gain any 2 cubes instead of 1.'},    
    {name: 'Patent License',	type: FundingType.Permanent,	effect: 'When another player buys an upgrade of a type you own gain +1 ⭐.'},        
    {name: FundingName.PreciseTools,	type: FundingType.Ongoing,	effect: 'When converting cubes with an upgrade you may change one cube in the result to any color.'},    
    {name: 'Maintenance Delay',	type: FundingType.Instant,	effect: 'Ignore an Employer Letter’s negative effect.'},            
]