import { FundingCard, FundingType } from "./components.js";

export enum FundingName {
    InvestorTrust = "Investor Trust",
    PreciseTools = "Precision Tools",
    MarketSurge = "Market Surge",
    CubeDraw = "Cube Draw",
    SharedUpgrade = "Shared Upgrade",
    PowerRefund = "Power Refund",
    PriorityWindow = "Priority Window",
    SelectiveDraw = "Selective Draw",
    ConverterVoucher = "Converter Voucher",
    VictoryResearch = "Victory Research",
    PowerSwap = "Power Swap",
    InvestorBonus = "Investor Bonus",
    ExtraTrapSlot = "Extra Trap Slot"
}

export const fundingCards: Partial<FundingCard>[] = [
    {name: FundingName.InvestorBonus,	type: FundingType.Instant,	effect: 'Gain +4 ⭐ for each upgrade you purchased this phase.'},
    {name: FundingName.ExtraTrapSlot,	type: FundingType.Permanent,	effect: 'Gain +1 storage slot (store 1 additional cube between rounds).'},
    {name: 'Emergency Reset',	type: FundingType.Instant,	effect: 'Immediately recover one token from your cooldown pool.'},
    {name: 'Investor Favor',	type: FundingType.Permanent,	effect: 'Gain +3 ⭐ whenever you buy an upgrade that costs 3 or more.'},
    {name: FundingName.CubeDraw,	type: FundingType.Permanent,	effect: 'When gaining cubes you may take them from 2 piles.  Combine those piles for other players after completion.'},
    {name: 'Selective Draw', type: FundingType.Instant,	effect: 'Place 2 blue cubes and 2 white cubes in the bag and mix.  Next, draw 4 cubes.'},
    {name: 'Power Refund',	type: FundingType.Permanent,	effect: 'After testing, keep one cube used for scoring.  You must have room for it in storage.'},
    {name: 'Mini-Storage',	type: FundingType.Permanent,	effect: 'You may store up to 2 blue cubes here between rounds.'},
    {name: 'Priority Window',	type: FundingType.Instant,	effect: 'Add +2 to your power when resolving Funding.'},
    {name: 'Loaned Technician',	type: FundingType.Ongoing,	effect: 'Use one upgrade on your board twice during the testing phase.'},
    {name: FundingName.SharedUpgrade,	type: FundingType.Permanent,	effect: 'Upgrades cost 1 less.'},
    {name: 'Converter Voucher',	type: FundingType.Ongoing,	effect: 'During testing, activate one upgrade without paying its requirement.'},
    {name: 'Market Peek',	type: FundingType.Permanent,	effect: 'When drawing random cards for upgrades: draw 2 upgrades, keep 1, and place the other on the bottom of the deck.'},
    {name: FundingName.PowerSwap,	type: FundingType.Instant,	effect: 'Move all tokens in your cooldown pool to your available pool.'},
    {name: 'Storage Insurance',	type: FundingType.Permanent,	effect: 'Gain 2 ⭐ for each leftover cube you don\'t store after testing.'},
    {name: 'R&D Grant',	type: FundingType.Instant,	effect: 'Draw 2 funding cards, keep 1, and discard the other.'},
    {name: 'Late-Stage Funding',	type: FundingType.Instant,	effect: 'In phase III, draw 2 funding cards.'},
    {name: 'Reagent Voucher',	type: FundingType.Ongoing,	effect: 'Take either 1 white or 1 blue cube from the pool each round.'},
    {name: 'Temporary Slot',	type: FundingType.Permanent,	effect: 'You may place an upgrade of any type here.'},
    {name: FundingName.MarketSurge,	type: FundingType.Permanent,	effect: 'When gaining cubes, take +1 (max 4) above the power assigned.'},
    {name: FundingName.VictoryResearch,	type: FundingType.Instant,	effect: 'Score 5 ⭐ immediately.'},
    {name: FundingName.InvestorTrust,	type: FundingType.Ongoing,	effect: 'Once per round, discard another funding card to gain any 2 cubes instead of 1.'},
    {name: 'Experimental Catalyst',	type: FundingType.Ongoing,	effect: 'Convert one cube of your choice into any color once per round.'},
    {name: 'Patent License',	type: FundingType.Permanent,	effect: 'When another player buys an upgrade of a type you own gain +1 ⭐.'},
    {name: 'Efficiency Audit',	type: FundingType.Permanent,	effect: 'Your upgrades that require 2 cubes now only require 1 cube (your choice).'},    
    {name: 'Backup Generator',	type: FundingType.Permanent,	effect: 'Your exhaust upgrade can be used an unlimited number of times during Testing.'},
    {name: FundingName.PreciseTools,	type: FundingType.Ongoing,	effect: 'When converting cubes with an upgrade you may change one cube in the result to any color.'},
    {name: 'Reactor Grant',	type: FundingType.Permanent,	effect: 'When using a Heater upgrade also gain +1 ⭐'},
    {name: 'Maintenance Delay',	type: FundingType.Instant,	effect: 'Ignore an Employer Letter’s negative effect.'},
    {name: 'Research Collaboration',	type: FundingType.Ongoing,	effect: 'During the Test phase copy the effect of one other player’s Trap upgrade.'},
    {name: 'Overclocked Reactor',	type: FundingType.Ongoing,	effect: 'Use one of the upgrades remaining in the market during testing.'},
    {name: 'Public Demonstration',	type: FundingType.Ongoing,	effect: 'Chose an upgrade to turn without using it and gain ⭐ equal to its cost.'},
]