import { CubeColor, UpgradeCard, UpgradeType } from "./components.js";

export const upgradeCards: Partial<UpgradeCard>[] = [
{stage: 1,	name: 'Bench Trap',	type: UpgradeType.trap,	effect: 'Gain ⬜',	cost: 3},
{stage: 1,	name: 'Primary Heater',	type: UpgradeType.heater,	effect: '⬜ 🟧 → 🟦 ✳️',	cost: 4},
{stage: 1,	name: 'Early Vent',	type: UpgradeType.exhaust,	effect: '🟧 → ⭐',	cost: 2},
{stage: 1,	name: 'Sapphire Cooler',	type: UpgradeType.cooling,	effect: '⬜ → 🟫 ⭐',	cost: 2},
{stage: 1,	name: 'GaN Cooler',	type: UpgradeType.cooling,	effect: '🟦 → 🟧 ⭐',	cost: 2},
{stage: 1,	name: 'Sapphire Exhaust',	type: UpgradeType.exhaust,	effect: '⬜ → ⭐',	cost: 2},
{stage: 1,	name: 'Startup Injection',	type: UpgradeType.injection,	effect: '✳️ → 🟫 🟧',	cost: 4},
{stage: 1,	name: 'Precursor Injection',	type: UpgradeType.injection,	effect: '✳️ → ⬜ 🟧',	cost: 4},
{stage: 1,	name: 'Two-Flow Nozzle',	type: UpgradeType.nozzle,	effect: '🟦 → 🟦 🟦',	cost: 4},
{stage: 1,	name: 'ZnSe Nozzle',	type: UpgradeType.nozzle,	effect: '🟧 → 🟧 🟧',	cost: 2},
{stage: 1,	name: 'Vacuum Nozzle',	type: UpgradeType.nozzle,	effect: '🟫 → 🟫 🟫',	cost: 2},
{stage: 1,	name: 'GaN Pump',	type: UpgradeType.pump,	effect: '⬜ → 🟧 🟦',	cost: 3},
{stage: 1,	name: 'ZnSe Pump',	type: UpgradeType.pump,	effect: '🟧 → ⬜ 🟦',	cost: 4},
{stage: 1,	name: 'Crystal Pump',	type: UpgradeType.pump,	effect: '🟫 → ⬜ 🟧',	cost: 3},
{stage: 1,	name: 'Prototype Pump',	type: UpgradeType.pump,	effect: '⬜ → 🟧 🟫',	cost: 2},
{stage: 1,	name: 'Vacuum Trap',	type: UpgradeType.trap,	effect: 'Gain 🟫',	cost: 2},
{stage: 2,	name: 'Bandgap Cooler',	type: UpgradeType.cooling,	effect: '🟥 → ⬛ ⭐',	cost: 1},
{stage: 2,	name: 'Stabilizer Cooler',	type: UpgradeType.cooling,	effect: '⬛ → 🟦 ⭐',	cost: 1},
{stage: 2,	name: 'Blue Cooler',	type: UpgradeType.cooling,	effect: '🟦 → 🟧 ⭐',	cost: 1},
{stage: 2,	name: 'Ion Cooler',	type: UpgradeType.cooling,	effect: '⬛ → 🟥 ⭐',	cost: 1},
{stage: 2,	name: 'Exhaust Vent',	type: UpgradeType.exhaust,	effect: '🟦 → ⭐⭐',	cost: 1},
{stage: 2,	name: 'Thermal Exhaust',	type: UpgradeType.exhaust,	effect: '⬛ → ⭐⭐⭐',	cost: 1},
{stage: 2,	name: 'Dopant Exhaust',	type: UpgradeType.exhaust,	effect: '🟥 → ⭐⭐⭐',	cost: 1},
{stage: 2,	name: 'Vacuum Exhaust',	type: UpgradeType.exhaust,	effect: '🟧 → ⭐⭐⭐',	cost: 2},
{stage: 2,	name: 'Annealing Heater',	type: UpgradeType.heater,	effect: '🟦 ⬜ → 🟥 ✳️',	cost: 3},
{stage: 2,	name: 'Bandgap Heater',	type: UpgradeType.heater,	effect: '⬛ 🟦 → 🟥 ✳️',	cost: 2},
{stage: 2,	name: 'Impurity Heater',	type: UpgradeType.heater,	effect: '🟫 ⬜ → 🟦 ✳️',	cost: 3},
{stage: 2,	name: 'Thermal Heater',	type: UpgradeType.heater,	effect: '🟧 🟦 → ⬛ ✳️',	cost: 2},
{stage: 2,	name: 'Diffusion Heater',	type: UpgradeType.heater,	effect: '🟦 🟥 → ⬛ ✳️',	cost: 1},
{stage: 2,	name: 'Dopant Heater II',	type: UpgradeType.heater,	effect: '🟥 ⬛ → 🟦 ✳️',	cost: 1},
{stage: 2,	name: 'Nitrogen Injection',	type: UpgradeType.injection,	effect: '✳️ → 🟦 🟥',	cost: 4},
{stage: 2,	name: 'Gas Injection',	type: UpgradeType.injection,	effect: '✳️ → ⬛ 🟥',	cost: 4},
{stage: 2,	name: 'Buffer Injection',	type: UpgradeType.injection,	effect: '✳️ → ⬜ 🟦',	cost: 4},
{stage: 2,	name: 'Mg Nozzle',	type: UpgradeType.nozzle,	effect: '⬛ → ⬛ ⬛',	cost: 1},
{stage: 2,	name: 'Red Nozzle',	type: UpgradeType.nozzle,	effect: '🟥 → 🟥 🟥',	cost: 2},
{stage: 2,	name: 'GaN Nozzle II',	type: UpgradeType.nozzle,	effect: '🟦 → 🟦 🟦',	cost: 3},
{stage: 2,	name: 'Purity Nozzle',	type: UpgradeType.nozzle,	effect: '⬜ → ⬜ ⬜',	cost: 3},
{stage: 2,	name: 'Alloy Nozzle',	type: UpgradeType.nozzle,	effect: '🟧 → 🟧 🟧',	cost: 1},
{stage: 2,	name: 'Diffusion Pump',	type: UpgradeType.pump,	effect: '🟦 → ⬛ ⬜',	cost: 2},
{stage: 2,	name: 'Alloy Pump',	type: UpgradeType.pump,	effect: '⬜ → 🟧 ⬛',	cost: 1},
{stage: 2,	name: 'Dopant Pump',	type: UpgradeType.pump,	effect: '⬛ → 🟥 🟦',	cost: 2},
{stage: 2,	name: 'ZnSe Pump II',	type: UpgradeType.pump,	effect: '🟧 → ⬜ 🟥',	cost: 3},
{stage: 2,	name: 'Red Pump',	type: UpgradeType.pump,	effect: '🟥 → ⬛ 🟦',	cost: 1},
{stage: 2,	name: 'Dual Flow Pump',	type: UpgradeType.pump,	effect: '🟦 → 🟥 ⬛',	cost: 2},
{stage: 2,	name: 'Recycle Pump',	type: UpgradeType.pump,	effect: '⬛ → ⬜ 🟧',	cost: 1},
{stage: 2,	name: 'Ga Trap',	type: UpgradeType.trap,	effect: 'Gain 🟥',	cost: 2},
{stage: 2,	name: 'Thermal Trap',	type: UpgradeType.trap,	effect: 'Gain ⬛',	cost: 1},
{stage: 2,	name: 'Twin Chamber Trap',	type: UpgradeType.trap,	effect: 'Gain 🟦',	cost: 2},
{stage: 3,	name: 'Photon Cooler',	type: UpgradeType.cooling,	effect: '🟨 → 🟥 ⭐',	cost: 1},
{stage: 3,	name: 'Indium Cooler',	type: UpgradeType.cooling,	effect: '🟨 → ⬛ ⭐',	cost: 1},
{stage: 3,	name: 'Stabilized Cooler',	type: UpgradeType.cooling,	effect: '🟨 → 🟦 ⭐',	cost: 1},
{stage: 3,	name: 'Hot Exhaust',	type: UpgradeType.exhaust,	effect: '🟥 → ⭐⭐⭐⭐',	cost: 1},
{stage: 3,	name: 'Photon Exhaust II',	type: UpgradeType.exhaust,	effect: '🟨 → ⭐⭐⭐⭐',	cost: 1},
{stage: 3,	name: 'Photon Vent',	type: UpgradeType.exhaust,	effect: '⬛ → ⭐⭐⭐⭐',	cost: 1},
{stage: 3,	name: 'Photon Heater',	type: UpgradeType.heater,	effect: '🟥 ⬛ → 🟨 ✳️',	cost: 1},
{stage: 3,	name: 'Indium Heater',	type: UpgradeType.heater,	effect: '⬛ 🟦 → 🟨 ✳️',	cost: 2},
{stage: 3,	name: 'Quantum Heater',	type: UpgradeType.heater,	effect: '🟦 ⬜ → 🟨 ✳️',	cost: 3},
{stage: 3,	name: 'Laser Heater',	type: UpgradeType.heater,	effect: '🟨 🟥 → 🟨 ✳️',	cost: 1},
{stage: 3,	name: 'Crystal Heater',	type: UpgradeType.heater,	effect: '🟥 🟦 → 🟨 ✳️',	cost: 2},
{stage: 3,	name: 'Indium Injection',	type: UpgradeType.injection,	effect: '✳️ → 🟨 🟥',	cost: 4},
{stage: 3,	name: 'Indium Injection II',	type: UpgradeType.injection,	effect: '✳️ → 🟨 🟦',	cost: 4},
{stage: 3,	name: 'Quantum Injection',	type: UpgradeType.injection,	effect: '✳️ → 🟦 🟨',	cost: 4},
{stage: 3,	name: 'Indium Nozzle',	type: UpgradeType.nozzle,	effect: '🟥 → 🟥 🟥',	cost: 1},
{stage: 3,	name: 'Quantum Nozzle',	type: UpgradeType.nozzle,	effect: '⬜ → ⬜ ⬜',	cost: 2},
{stage: 3,	name: 'Final Nozzle',	type: UpgradeType.nozzle,	effect: '🟨 → 🟨 🟨',	cost: 2},
{stage: 3,	name: 'Quantum Pump',	type: UpgradeType.pump,	effect: '🟦 → 🟨 ⬛',	cost: 2},
{stage: 3,	name: 'Photon Pump',	type: UpgradeType.pump,	effect: '⬜ → 🟨 🟦',	cost: 3},
{stage: 3,	name: 'Indium Pump',	type: UpgradeType.pump,	effect: '🟥 → 🟨 ⬜',	cost: 2},
]
